### ISSUE TITLE
Bug: Adding notes with `add-from-files` gives them all the "marked" tag

### ISSUE THREAD

**Issue by ckp95** [lervag/apy#17] opened 2020-06-06 18:45 UTC
I make a file called `stuff.md`

```
model: Basic
deck: All

# Note

## Front

sphinx of black quartz

## Back

judge my vow!
```

I add it to Anki using

`apy add-from-file stuff.md`

this gives:

```
reverting to stock json
Added note to deck: All
Review added notes? [y/N]: n
Database was modified.
Remember to sync!
```

When I open my Anki database, the note appears but it has the "marked" tag, which I didn't specify and don't want.

![image](https://user-images.githubusercontent.com/43073868/83952052-ef4cbd80-a82d-11ea-943c-7c16dabf6c84.png)

This doesn't happen when I use `apy add` and use the interactive mode.

**Comment by lervag** [comment] 2020-06-06 18:49
Are you using the most recent version of apy? I think I fixed this issue some time ago.

**Comment by ckp95** [comment] 2020-06-06 18:58
I installed using

`/usr/bin/python -m pip install --user git+https://github.com/lervag/apy.git#egg=apy`

today, so it should be the latest version. I just tried uninstalling and reinstalling, and trying again with a new markdown file: same problem.

**Comment by lervag** [comment] 2020-06-06 19:01
Ah, I see. This means, I think, that you are on the version tagged 0.4, and not on the most recent committed version (easy to verify: your commit to the README is the latest commit).

I'll look into it and see if I can reproduce.

**Comment by lervag** [comment] 2020-06-06 19:04
The function `markdown_file_to_notes` specifies the `marked` tag as default if there is no other tag specified. I assume this is an unexpected and unwanted behaviour? What would be the expected behaviour? Perhaps just add no tags unless explicitly tagged either in the notes file or with the `-t` option?

The reason I've not noticed the issue is because I tend to always include at least one tag.

**Comment by ckp95** [comment] 2020-06-06 19:06
>Ah, I see. This means, I think, that you are on the version tagged 0.4, and not on the most recent committed version (easy to verify: your commit to the README is the latest commit).

It would be good to have a `--version` option as well so people can check :) 

>The function markdown_file_to_notes specifies the marked tag as default if there is no other tag specified. I assume this is an unexpected and unwanted behaviour? What would be the expected behaviour? Perhaps just add no tags unless explicitly tagged either in the notes file or with the -t option?

Yeah I expected there to be no tags by default. I organize my notes mostly by subdecks rather than tags, so most of them are untagged. The `marked` tag also causes notes to be highlighted in the card browser which is slightly annoying.

Maybe this could be an option in the config?

**Comment by lervag** [comment] 2020-06-06 20:24
> It would be good to have a `--version` option as well so people can check :)

Agreed. I'll add it.

> Yeah I expected there to be no tags by default. I organize my notes mostly by subdecks rather than tags, so most of them are untagged. The `marked` tag also causes notes to be highlighted in the card browser which is slightly annoying.
> 
> Maybe this could be an option in the config?

I think the simple solution is to remove the default marked tag. If someone wants to have a default tag option in the config, then I guess they'll suggest it. I don't quite see the need for it and I don't want to add options unless they're used by anyone.

**Closed** 2020-06-06 20:26 UTC

**Comment by ckp95** [comment] 2020-06-07 12:27
This is still broken, I get a traceback when I try with no tags:

```
model: Basic
deck: All
tags: 

# Note

## Front

lets see what happens if

## Back

there are no tags
```

```
[ckp95@ckp95-laptop anki]$ apy add-from-file stuff.md 
reverting to stock json
Traceback (most recent call last):
  File "/home/ckp95/.local/bin/apy", line 8, in <module>
    sys.exit(main())
  File "/home/ckp95/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ckp95/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ckp95/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ckp95/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ckp95/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ckp95/.local/lib/python3.8/site-packages/apy/cli.py", line 105, in add_from_file
    notes = a.add_notes_from_file(file, tags)
  File "/home/ckp95/.local/lib/python3.8/site-packages/apy/anki.py", line 382, in add_notes_from_file
    return self.add_notes_from_list(markdown_file_to_notes(filename),
  File "/home/ckp95/.local/lib/python3.8/site-packages/apy/anki.py", line 407, in add_notes_from_list
    f"{tags} {note['tags']}",
KeyError: 'tags'
```

**Comment by lervag** [comment] 2020-06-07 13:26
I think my latest commit fixes this.

**Comment by ckp95** [comment] 2020-06-07 16:17
Yep, thanks!

**Comment by lervag** [comment] 2020-06-07 16:26
No problem :)
