### ISSUE TITLE
Error on apy --help

### ISSUE THREAD

**Issue by michaelsjackson** [lervag/apy#14] opened 2020-05-29 20:28 UTC
Python 3.7.4
Ubuntu 18.04

```
> apy --help
Traceback (most recent call last):
  File "/home/me/miniconda3/bin/apy", line 11, in <module>
    load_entry_point('apy', 'console_scripts', 'apy')()
  File "/home/me/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/me/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/me/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/me/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/me/code/apy/apy/cli.py", line 6, in <module>
    from apy.anki import Anki
  File "/home/me/code/apy/apy/anki.py", line 10, in <module>
    from aqt.profiles import ProfileManager
  File "/usr/share/anki/aqt/__init__.py", line 14, in <module>
    from aqt.qt import *
  File "/usr/share/anki/aqt/qt.py", line 6, in <module>
    import sip
ModuleNotFoundError: No module named 'sip'
```

But I installed sip, strange, any hints, thanks in advance.

**Comment by michaelsjackson** [comment] 2020-05-29 22:15
Version 2.1.22 (0ecc189a)
Python 3.8.1 Qt 5.14.1 PyQt 5.14.1

**Comment by lervag** [comment] 2020-05-30 05:59
> Does it work if you import sip in a simple python repl?

Also: Which version of `apy` are you using? `apy` needs to be adapted to Anki. The latest version of `apy` supports Anki 2.1.26. Version 0.2 supports Anki 2.1.23, and it could be necessary to downgrade.

**Comment by michaelsjackson** [comment] 2020-05-30 09:47
Oh, I see, I took the latest stable Anki, let me try the newest Anki then first quickly.

**Comment by michaelsjackson** [comment] 2020-05-30 09:55
I guess it can be something I am using miniconda python, maybe?  Updated to latest Anki, still same.

**Comment by michaelsjackson** [comment] 2020-05-30 13:11
Regarding which apy version, I installed latest version with:
```
# Install latest version
pip install --user git+https://github.com/lervag/apy.git#egg=apy
```

Regarding repl how to test sip?

**Comment by michaelsjackson** [comment] 2020-05-30 13:51
Can different python versions cause this problem?

Anki says:
```
Version 2.1.26 (70784154)
Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
```

My terminal says:
```
python --version
Python 3.7.4
```

Might this be causing my above troble with sip maybe?  I wished programs used the oldest features of programming languages, not always the latest, like from python 1.0, so it would work with any python version, and not only with the latest.  I am not even sure for what sip module is needed at all, if this would be a minor feature for example, just because of this tiny thing, the whole app's functionality is blocked, very bad decision, if so.

**Comment by lervag** [comment] 2020-05-30 21:06
> I guess it can be something I am using miniconda python, maybe? Updated to latest Anki, still same.
> ...
> Can different python versions cause this problem?

Yes, definitely. It seems you are running Anki in a different "environment" than the python in your shell.

In particular, your are running `apy` within a Python 3.7 `miniconda` environment. OTOH, it seems Anki is running with your system Python, which seems to be Python 3.8.

You say early "But I installed sip", but when you do

> ```
> python
> Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
> [GCC 7.3.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import sip
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'sip'
> ```

you also clearly show that `sip` is not installed.

My suggestion would be to have `apy` and Anki within the same Python version, or at least to install `sip` within the Python environment that runs `apy`.

**Comment by michaelsjackson** [comment] 2020-05-30 22:16
```
 /home/me/miniconda3/bin/python -m pip install sip
Requirement already satisfied: sip in ./miniconda3/lib/python3.7/site-packages (5.2.0)
Requirement already satisfied: packaging in ./miniconda3/lib/python3.7/site-packages (from sip) (20.4)
Requirement already satisfied: toml in ./miniconda3/lib/python3.7/site-packages (from sip) (0.10.1)
Requirement already satisfied: six in ./miniconda3/lib/python3.7/site-packages (from packaging->sip) (1.12.0)
Requirement already satisfied: pyparsing>=2.0.2 in ./miniconda3/lib/python3.7/site-packages (from packaging->sip) (2.4.6)

```

Without miniconda in path:
```

pip install sip
Requirement already satisfied: sip in ./miniconda3/lib/python3.7/site-packages (5.2.0)
Requirement already satisfied: toml in ./miniconda3/lib/python3.7/site-packages (from sip) (0.10.1)
Requirement already satisfied: packaging in ./miniconda3/lib/python3.7/site-packages (from sip) (20.4)
Requirement already satisfied: pyparsing>=2.0.2 in ./miniconda3/lib/python3.7/site-packages (from packaging->sip) (2.4.6)
Requirement already satisfied: six in ./miniconda3/lib/python3.7/site-packages (from packaging->sip) (1.12.0)
```

So how can I install sip other than above?

**Comment by lervag** [comment] 2020-05-30 22:19
I have to admit I don't know. I've never seen this issue, and I have never used conda. Sorry! :\

**Comment by michaelsjackson** [comment] 2020-05-31 10:48
No problem, thanks for your help, when I have a bit more time, I will experiment here a bit more, enough for now.   I will try getting image upload working in anki-editor, yesterday this worked, now with latest Anki it seems not to work again, so need to downgrade Anki to latest stable and see if images will work with anki-editor again.  Then I will stick to that for some time.  

Probably we will have a few more Anki related solution over the next monts/years, I guess. Because it is too cool.  Have a nice day my friend and thanks for sharing your work.

**Comment by lervag** [comment] 2020-05-31 20:53
Happy to help. I'll take the liberty of closing the issue, but feel free to reopen (or open a new) if you can provide more details.

I still believe this has something to do with your python environments. It seems you are using several environments through conda, and that there is a conflict between the environment used when you run `apy` and the environment where `anki` is installed. However, it is difficult to know more for now. Sorry.

> Have a nice day my friend and thanks for sharing your work.

Happy to share, and thanks! :)

**Closed by lervag** 2020-05-31 20:53 UTC

**Comment by S4GU4R0** [comment] 2024-07-13 07:26
I 

> Python 3.7.4 Ubuntu 18.04
> 
> ```
> > apy --help
> Traceback (most recent call last):
>   File "/home/me/miniconda3/bin/apy", line 11, in <module>
>     load_entry_point('apy', 'console_scripts', 'apy')()
>   File "/home/me/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/home/me/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
>     return ep.load()
>   File "/home/me/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
>     return self.resolve()
>   File "/home/me/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/home/me/code/apy/apy/cli.py", line 6, in <module>
>     from apy.anki import Anki
>   File "/home/me/code/apy/apy/anki.py", line 10, in <module>
>     from aqt.profiles import ProfileManager
>   File "/usr/share/anki/aqt/__init__.py", line 14, in <module>
>     from aqt.qt import *
>   File "/usr/share/anki/aqt/qt.py", line 6, in <module>
>     import sip
> ModuleNotFoundError: No module named 'sip'
> ```
> 
> But I installed sip, strange, any hints, thanks in advance.

I am having this exact same issue but not using conda. I just installed Anki, apy, and sip, so everything is as-is out of the box. using ubuntu lts. not sure what's up, but i saw it recommended on reddit and thought i'd try it. but unfortunately no luck.

**Comment by lervag** [comment] 2024-07-13 07:37
> I am having this exact same issue but not using conda. I just installed Anki, apy, and sip, so everything is as-is out of the box. using ubuntu lts. not sure what's up, but i saw it recommended on reddit and thought i'd try it. but unfortunately no luck.

I think you did not install it as suggested in the README file: https://github.com/lervag/apy/blob/29f6d8a4a5aa2750baf5046090bedf8e54e6fc19/README.md?plain=1#L23

I recommend `pipx`, as it will install `apy` in a separate Python environment. But it should work if you use `pip` as well.

**Comment by S4GU4R0** [comment] 2024-07-13 09:44
So, it turned out to be the Anki installation that was the cause. I had
installed Anki through the app store, which apparently has issues that I
didn't know about. The Anki site recommends installing from them directly
for consistency. Tried reinstalling apy right after fixing Anki, and now it
works great out of the box. Thanks for the prompt reply!

**Comment by lervag** [comment] 2024-07-13 09:51
No problem, and glad to hear it works now!
